server:
  port: 8008

spring:
  application:
    name: note
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leetcode?serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    virtual-host: /
    username: admin
    password: 123456
    port: 5672
    host: 127.0.0.1


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xingxin.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log4j2.xml
